//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackballScroll.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrackballScroll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About TrackballScroll.
        /// </summary>
        internal static string TextButtonAbout {
            get {
                return ResourceManager.GetString("TextButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TextButtonExit {
            get {
                return ResourceManager.GetString("TextButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused (click to resume).
        /// </summary>
        internal static string TextButtonHookDisabled {
            get {
                return ResourceManager.GetString("TextButtonHookDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled (click to pause).
        /// </summary>
        internal static string TextButtonHookEnabled {
            get {
                return ResourceManager.GetString("TextButtonHookEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer vertical/horizontal movement (disabled).
        /// </summary>
        internal static string TextButtonPreferAxisDisabled {
            get {
                return ResourceManager.GetString("TextButtonPreferAxisDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer vertical/horizontal movement.
        /// </summary>
        internal static string TextButtonPreferAxisEnabled {
            get {
                return ResourceManager.GetString("TextButtonPreferAxisEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrackballScroll v2.1.1
        ///Copyright (c) 2016, 2017 Martin Seelge
        ///Project URL: https://github.com/Seelge/TrackballScroll/
        ///
        ///Scroll with your trackball / mouse movement when holding down button 3 or 4.
        ///See README.md for additional information.
        ///
        ///License: The MIT License
        ///https://github.com/Seelge/TrackballScroll/blob/master/LICENSE.
        /// </summary>
        internal static string TextMessageBoxAbout {
            get {
                return ResourceManager.GetString("TextMessageBoxAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrackballScroll.
        /// </summary>
        internal static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
    }
}
